### ISSUE TITLE
Possible to schedule more frequently?

### ISSUE THREAD

**Issue by techieshark** [SalesforceLabs/Salesforce-PayPal-Transaction-Connector#1]
Hi, thanks for this awesome looking project.

Would you be able to say a) if it is possible to change the schedule to run more frequently - perhaps hourly even? and if so, b) how?

Thanks!

**Comment by techieshark** [comment]
@tepp0f3l @mohamearif tagging you assuming you are the maintainers here. 

Also some meta questions - I'm curious if Salesforce is supporting this project, and I'm curious if you'd accept PRs.

**Comment by tepp0f3l** [comment]
Yes I believe @mohamearif is the creator of the code in this repo, and can respond on whether they're actively maintaining the project and are accepting suggestions/PRs.

In general, all projects in the SalesforceLabs Github are **not** officially-supported by Salesforce, but they are created by Salesforce employees and product teams who offer varying degrees of engagement and updates.

**Comment by mohamearif** [comment]
Hi @techieshark 

I apologize for the delayed response. Since this is an open-source project, you can delete the existing scheduled job in your organization and create a new one by modifying/running the Apex script provided [here](https://github.com/SalesforceLabs/Salesforce-PayPal-Transaction-Connector/blob/main/scripts/apex/PostDeploymentScript.apex).

If you plan to run the job hourly, I recommend checking your organization's governor limits to ensure that these hourly scheduled Apex queueable and callouts won't cause any issues.

Additionally, changing your scheduling requirements doesn't require a pull request. Since this is open source within your organization, you can modify it as needed without having to update the GitHub source for your specific needs.

Thanks, and I hope this helps!

CC: @tepp0f3l

**Comment by techieshark** [comment]
Awesome, thanks very much @mohamearif and @tepp0f3l !
